StoreOutline2/Areas/Admin/Controllers/ManageProductsController.cs
using DataManager.Library.DataAccess;
using DataManager.Library.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using StoreOutline2.Areas.Admin.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace StoreOutline2.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("[area]/[controller]/[action]")]
    public class ManageProductsController : Controller
    {
        IGeneralDetails_Data _genDetails_Data;
        IProducts_Data _products_Data;
        IBrand_Data _brand_Data;
        IProductClass_Data _gen_Data;
        IProductType_Data _sub_Data;
        ILogger<ManageProductsController> _logger;
        LoggingHelper<ManageProductsController> _logging;

        public ManageProductsController(ILogger<ManageProductsController> logger, IProducts_Data products_Data
            , IBrand_Data brand_Data, IProductClass_Data generalType_Data, IProductType_Data subType_Data,
            IGeneralDetails_Data genDetails_Data)
        {
            _products_Data = products_Data;
            _brand_Data = brand_Data;
            _gen_Data = generalType_Data;
            _sub_Data = subType_Data;
            _genDetails_Data = genDetails_Data;
            _logger = logger;
            _logging = new LoggingHelper<ManageProductsController>("Admin/ManageProducts/", _logger);
        }

        public IActionResult Index()
        {
            _logging.CurrentAddress = nameof(Index);
            _logging.Address();
            return View();
        }





        [HttpGet]
        public IActionResult NewProductInformation()
        {
            _logging.CurrentAddress = nameof(NewProductInformation) + "[GET]";
            _logging.InformationLog("Product instance instantiated.");
            return View();
        }
    }
}

StoreOutline2/Areas/Admin/Controllers/ProductInfoManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataManager.Library.DataAccess;
using DataManager.Library.Helper;
using DataManager.Library.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using StoreOutline2.Areas.Admin.Models;

namespace StoreOutline2.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("[area]/[controller]/[action]")]
    public class ProductInfoManagerController : Controller
    {
        private string _tempKey = "message";
        private IConfiguration _config;
        private IBrand_Data _brand_Data;
        private IProductClass_Data _productClass_Data;
        private IProductType_Data _productType_Data;
        private IPIM_Helper _pim_Helper;
        public ProductInfoManagerController(IConfiguration config,
            IBrand_Data brand_Data, IProductClass_Data genTypeData, IProductType_Data subType_Data,
            IPIM_Helper pim_Helper)
        {
            _config = config;
            _brand_Data = brand_Data;
            _productClass_Data = genTypeData;
            _productType_Data = subType_Data;
            _pim_Helper = pim_Helper;
        }
        public IActionResult Index()
        {
            return View();
        }






        string duplicateErrorMessage = "This value already exists in the database: ";

        /// Brand
        /// 
        /// 
        /// 
        [HttpGet]
        public IActionResult AddEditBrand(int? id)
        {
            if (id != null)
            {
                ViewBag.AddEdit = "Edit";
                var brandModel = _brand_Data.GetById((int)id);
                ViewBag.Name = brandModel.Name;
                return View(brandModel);
            }
            else
            {
                ViewBag.AddEdit = "Add";
                return View();
            }

        }
        [HttpPost]
        public IActionResult AddEditBrand(BrandModel brandModel)
        {
            if (ModelState.IsValid)
            {
                if (brandModel.Id != null)
                {
                    _brand_Data.Edit(brandModel);
                    TempData[_tempKey] = $"Succesfully edited Brand: {brandModel.Name.ToUpper()}";
                    return RedirectToAction("Index");
                }
                if (_pim_Helper.PIMOnly_GetAllBrandClassTypeNames().Exists(x => x.ToUpper() == brandModel.Name.ToUpper()))
                {
                    ModelState.AddModelError("",duplicateErrorMessage + brandModel.Name);
                    return View(brandModel);
                }
                else
                {
                    _brand_Data.Save(brandModel);
                    TempData[_tempKey] = $"Successfully Added new Brand: {brandModel.Name}";
                    return RedirectToAction("Index");
                }

            }
            else
            {
                return View(brandModel);
            }
        }
        public IActionResult BrandList()
        {
            var brandModelList = _brand_Data.GetAll();
            return View(brandModelList);
        }







        /// Product Class
        /// 
        /// 
        /// 
        [HttpGet]
        public IActionResult AddEditProductClass(int? id)
        {
            if (id != null)
            {
                ViewBag.AddEdit = "Edit";
                var prodClassModel = _productClass_Data.GetById((int)id);
                ViewBag.Name = prodClassModel.ClassName;
                return View(prodClassModel);
            }
            else
            {
                ViewBag.AddEdit = "Add";
                return View();
            }

        }
        [HttpPost]
        public IActionResult AddEditProductClass(ProductClassModel productClassModel)
        {
            if (ModelState.IsValid)
            {
                if (productClassModel.Id != null)
                {
                    _productClass_Data.Edit(productClassModel);
                    TempData[_tempKey] = $"Succesfully edited Product Class: {productClassModel.ClassName.ToUpper()}.";
                    return RedirectToAction("Index");
                }
                if (_pim_Helper.PIMOnly_GetAllBrandClassTypeNames().Exists(x => x.ToUpper() == productClassModel.ClassName.ToUpper()))
                {
                    ModelState.AddModelError("", duplicateErrorMessage + productClassModel.ClassName);
                    return View(productClassModel);
                }
                else
                {
                    _productClass_Data.Save(productClassModel);
                    TempData[_tempKey] = $"Successfully added new Product Class: {productClassModel.ClassName.ToUpper()}.";
                    return RedirectToAction("Index");
                }
            }
            else
            {
                return View(productClassModel);
            }
        }

        public IActionResult ProductClassList()
        {
            var productClassModelList = _productClass_Data.GetAll();
            return View(productClassModelList);
        }






        /// Product Type
        /// 
        /// 
        /// 
        [HttpGet]
        public IActionResult AddEditProductType(int? id)
        {
            IActionResult result = View();
            if (id != null)
            {
                ViewBag.AddEdit = "Edit";
                var productType = _productType_Data.GetById((int)id);
                ViewBag.Name = productType.Type;
                result = View(productType);
            }
            else
            {
                ViewBag.AddEdit = "Add";
                result = View();
            }
            ViewBag.classList = _productClass_Data.GetAll();
            return result;
        }
        [HttpPost]
        public IActionResult AddEditProductType(ProductTypeModel productTypeModel)
        {
            IActionResult result = View();
            if (ModelState.IsValid)
            {
                if (productTypeModel.Id != null)
                {
                    _productType_Data.Edit(productTypeModel);
                    TempData[_tempKey] = $"Successfully edited Product Type: {productTypeModel.Type}";
                    result = RedirectToAction("ProductType_List");
                }
                if (_pim_Helper.PIMOnly_GetAllBrandClassTypeNames().Exists(x => x.ToUpper() == productTypeModel.Type.ToUpper()))
                {
                    ModelState.AddModelError("", duplicateErrorMessage + productTypeModel.Type);
                    result = View(productTypeModel);
                }
                else
                {
                    _productType_Data.Save(productTypeModel);
                    TempData[_tempKey] = $"Successfully saved Product Type: {productTypeModel.Type}";
                    result = RedirectToAction("Index");
                }
            }
            else
            {
                
                result = View(productTypeModel);
            }
            ViewBag.ClassList = _productClass_Data.GetAll();
            return result;
        }






        ///NOTE: Get rid of GetListOfTypeWithClassAssociated and reuse other storage procedures.
        public IActionResult ProductTypeList()
        {
            var productTypeList = _productType_Data.GetAll();
            productTypeList
                .ForEach(x => 
                {
                    x.ProductClass = _productClass_Data.GetById(x.ProductClass_Id);
                });
            return View(productTypeList);
        }






























        [HttpGet]
        public IActionResult Delete(string category, int id, string name)
        {

            return View(new DeleteModel { Category = category, Id = id, Name = name });
        }
        [HttpPost]
        public IActionResult Delete(DeleteModel deleteModel)
        {
            IActionResult result = View(deleteModel);

            if (deleteModel.Category == "Brand")
            {
                _brand_Data.Delete(deleteModel.Id);
                result = RedirectToAction("BrandList");
            }
            else if (deleteModel.Category == "GeneralType")
            {
                _productClass_Data.Delete(deleteModel.Id);
                result = RedirectToAction("GeneralTypeList");
            }
            else if (deleteModel.Category == "SubType")
            {
                _productType_Data.Delete(deleteModel.Id);
                result = RedirectToAction("SubTypeList");
            }
            else
            {
                result = View(deleteModel);
            }
            TempData["deleted"] = $"{deleteModel.Name} has been deleted";
            return result;

        }

    }
}

StoreOutline2/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>


    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.79.0">

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/blog-rtl/">



    <!-- Bootstrap core CSS -->
    @*<link href="~/css/bootstrap.rtl.min.css" rel="stylesheet">*@
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Amiri:wght@400;700&amp;display=swap" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="~/css/blog.rtl.css" rel="stylesheet">
    <link href="~/css/CustomStyles.css?v=8" rel="stylesheet" />
</head>
<body>
    <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">ALVEYS</a>
        <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
        <ul class="navbar-nav px-3">
            <li class="nav-item text-nowrap">
                <a class="nav-link" href="#">Sign out</a>
            </li>
        </ul>
    </header>
    <div class="container-fluid">
        <div class="row">
            <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
                <div class="position-sticky pt-3">
                    <ul class="nav flex-column">

                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="Home" asp-action="Index">
                                <span data-feather="file"></span>
                                Home
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" asp-controller="ManageProducts" asp-action="Index">
                                @*<span data-feather="home"></span>*@
                                Manage Products
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="ProductInfoManager" asp-action="Index">
                                Product Info Manager
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="bar-chart-2"></span>
                                Reports
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="layers"></span>
                                Integrations
                            </a>
                        </li>
                    </ul>

                    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                        <span>Saved reports</span>
                        <a class="link-secondary" href="#" aria-label="Add a new report">
                            <span data-feather="plus-circle"></span>
                        </a>
                    </h6>
                    <ul class="nav flex-column mb-2">
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="file-text"></span>
                                Current month
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="file-text"></span>
                                Last quarter
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="file-text"></span>
                                Social engagement
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="file-text"></span>
                                Year-end sale
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>

            <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
                <div>
                    @RenderBody()
                </div>
            </main>
        </div>
    </div>
    <script src="~/js/bootstrap.bundle.min.js"></script>
</body>
</html>